sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
env:
  - DJANGO='Django<1.6'
  - DJANGO='Django<1.7'
  - DJANGO='Django<1.8'
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO='Django<1.8'
install:
  - 'pip install "${DJANGO}"'
  - pip install coveralls
  - pip install -e .
script: ./runtests.sh -v
after_success:
  - coveralls
