language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
install:
  - "pip install ."
  - "pip install coveralls"
script: nosetests --with-coverage --cover-package=rules
after_success:
  coveralls
